[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pynetsnmp-2"
version = "0.1.10"
description = "ctypes wrapper for net-snmp"
readme = "README.md"
license = "GPL-2.0-or-later"
license-files = ["LICENSE.txt"]
requires-python = ">=3.9,<3.14"
keywords = ["snmp", "twisted", "pynetsnmp", "netsnmp"]
authors = [
    { name = "Zenoss", email = "support@zenoss.com" },
]
maintainers = [
    { name = "Morten Brekkevold", email = "morten.brekkevold@sikt.no" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: System :: Monitoring",
    "Topic :: System :: Networking :: Monitoring",
]
dependencies = [
    "Twisted",
]

[project.urls]
Homepage = "https://github.com/Uninett/pynetsnmp"

[tool.setuptools.packages.find]
include = ["pynetsnmp*"]
